"""change model user

Revision ID: 7591924c9c45
Revises: be583825bd9b
Create Date: 2025-05-26 18:50:41.885825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7591924c9c45'
down_revision: Union[str, None] = 'be583825bd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('photo_url', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
